vim.cmd("source ~/.vimrc")

require("user.options")
require("user.plugins")
require("user.autocommands")
require("user.impatient")
require("user.autopairs")
require("user.lualine")
require("user.cmp")
require("user.toggleterm")
require("user.lsp")
require("user.colorscheme")
require("user.treesitter")
require("user.telescope")
require("user.gitsigns")
