#!/usr/bin/env sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config external_bar all:26:0
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse autofocus
yabai -m config window_placement second_child
yabai -m config window_topmost on
yabai -m config window_shadow float
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_widow_opacity 0.85
yabai -m config window_border on
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff555555
yabai -m config insert_feedback_color 0xaad75f5f
yabai -m config split_ratio 0.50
yabai -m config auto_balance on
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 24
yabai -m config bottom_padding 24
yabai -m config left_padding 24
yabai -m config right_padding 24
yabai -m config window_gap 12

# mission-control desktop labels
yabai -m space 1 --label term
yabai -m space 2 --label dev
yabai -m space 3 --label comm
yabai -m space 4 --label zoom
yabai -m space 5 --label social
yabai -m space 6 --label media

# specific space settings
yabai -m config --space comm

# window rules
yabai -m rule --add app="^PyCharm$" space=dev
yabai -m rule --add app="^Microsoft Outlook$" space=comm
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Microsoft Excel$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Slack$" space=comm
yabai -m rule --add app="^zoom\.us$" space=zoom
yabai -m rule --add app="^Discord$" space=social
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^Notion$" manage=off
yabai -m rule --add app="Google Chrome"

# signals
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"

echo "yabai configuration loaded.."n
