#!/usr/bin/env zsh

git_current_branch() {
  local ref
  ref=$(GIT_OPTIONAL_LOCKS=0 git symbolic-ref --quiet HEAD 2> /dev/null)
  local ret=$?

  if [[ $ret != 0 ]]; then
    [[ $ret == 128 ]] && return  # no git repo.
    ref=$(GIT_OPTIONAL_LOCKS=0 git rev-parse --short HEAD 2> /dev/null) || return
  fi

  echo ${ref#refs/heads/}
}
