#!/usr/bin/env zsh

alias vi="nvim"
alias icat="kitty +kitten icat"
alias wgup="wg-quick up wg0"
alias wgdown="wg-quick down wg0"

# git
# Check if main exists and use instead of master
function git_main_branch() {
  command git rev-parse --git-dir &>/dev/null || return
  local ref
  for ref in refs/{heads,remotes/{origin,upstream}}/{main,trunk}; do
    if command git show-ref -q --verify $ref; then
      echo ${ref:t}
      return
    fi
  done
  echo master
}

alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gba='git branch -a'
alias gbd='git branch -d'
alias gbD='git branch -D'
alias gbl='git blame -b -w'
alias gc='git commit -v'
alias gco='git checkout'
alias gd='git diff'
alias gfo='git fetch origin'
alias gfa='git fetch --all --prune'
alias gpsup='git push --set-upstream origin $(git_current_branch)'
alias gl='git pull'
alias gm='git merge'
alias gmom='git merge origin/$(git_main_branch)'
alias gp='git push'
alias grhh='git reset --hard'
alias groh='git reset origin/$(git_current_branch) --hard'
alias gst='git status'

